services:
  web:
    build: ..
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - ${WEB_PORT}:${WEB_PORT}
  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: ${DB_DB}
      MARIADB_RANDOM_ROOT_PASSWORD: 1
    #ports:
    #  - 3306:3306
    healthcheck:
      interval: 15s
      retries: 3
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 30s
    volumes:
      - ${PWD}/nekretnine.sql:/docker-entrypoint-initdb.d/a.sql
      - ${PWD}/data.sql:/docker-entrypoint-initdb.d/b.sql
      #- /var/lib/mysql:/var/lib/mysql
